### PR TITLE
Fix label in project response.

### LINKED ISSUE #77: label field for projects shouldn't include organization
Currently the `label` in project includes the organization, e.g. `bbp/ephys`. It should only include the project part.

### PR DESCRIPTION
**Pull request by wwajerowicz**
Fixes #77

### CODE REVIEW

**Comment by bogdanromanx** [comment]
> wouldn't It be better for ProjectReference to be a case class with the ProjectReferenceId and a OrganizationReferenceId ?

I would very much prefer to avoid doing string split and get by index... so yeah, I'm voting for that as well.

File: modules/service/src/main/scala/ch/epfl/bluebrain/nexus/admin/service/routes/ProjectRoutes.scala [hunk 1]
```diff
@@ -54,8 +54,8 @@ final class ProjectRoutes(projects: Projects[Future])(implicit iamClient: IamCli
     new RoutesEncoder[Resource[ProjectReference]]()
   import encoders._
   private def readRoutes(implicit credentials: Option[OAuth2BearerToken]): Route =
-    (segment2(of[ProjectReference]) & pathEndOrSingleSlash) { name =>
-      (get & authorizeOn[HasReadProjects](name.value)) { implicit perms =>
+    (projectReference & pathEndOrSingleSlash) { name =>
+      (get & authorizeOn[HasReadProjects](name.show)) { implicit perms =>
```
Comment (umbreak) [inline modules/service/src/main/scala/ch/epfl/bluebrain/nexus/admin/service/routes/ProjectRoutes.scala]: You could avoid all this `authorizeOn` `.show` by modifying the string signature of [the authorizeOn method](https://github.com/wwajerowicz/nexus-admin/blob/1c3633b193574a7dd7cfa4b2abd43ac5026375ef/modules/service/src/main/scala/ch/epfl/bluebrain/nexus/admin/service/directives/AuthDirectives.scala#L84) to something like
```scala
def apply[F[_, _], P, A: Show](value: A)(
      implicit ev: F[FullAccessControlList, P] =:= FTP,
      rt: RefType[F],
      v: Validate[FullAccessControlList, P],
      client: IamClient[Future],
      cred: Option[OAuth2BearerToken]
  ): Directive1[FTP] = apply(Path(value.show))
```

File: modules/service/src/main/scala/ch/epfl/bluebrain/nexus/admin/service/routes/ProjectAclRoutes.scala [hunk 2]
```diff
@@ -34,14 +35,14 @@ final class ProjectAclRoutes(projects: Projects[Future], proxy: Proxy)(implicit
...
-    (segment2(of[ProjectReference]) & pathPrefix("acls") & pathEndOrSingleSlash) { name =>
+    (projectReference & pathPrefix("acls") & pathEndOrSingleSlash) { name =>
       (exists(name) & parameterMap & extractRequest) { (params, req) =>
         trace(s"${req.method.toString().toLowerCase()}ProjectACL") {
           complete(
             proxy(
               req
                 .withHeaders()
-                .withUri(iamUri.append("acls" / name.value).withQuery(Query(params)))
+                .withUri(iamUri.append("acls" / name.show).withQuery(Query(params)))
```
Comment (umbreak) [inline modules/service/src/main/scala/ch/epfl/bluebrain/nexus/admin/service/routes/ProjectAclRoutes.scala]: Is the `append` method, when passing a string with a slash, treating as a Path.Slash or it is URL encoding the slash because it thinks it belongs to the segment? I'm talking about the part on `name.show`

File: modules/service/src/main/scala/ch/epfl/bluebrain/nexus/admin/service/routes/ProjectRoutes.scala (hunk 1 above)
Comment (wwajerowicz) [reply modules/service/src/main/scala/ch/epfl/bluebrain/nexus/admin/service/routes/ProjectRoutes.scala]: But if you try `authorizeOn` and  pass `Path` object to the apply method e.g. 
```
(pathEndOrSingleSlash & authorizeOn[HasReadProjects](Path.Empty / "*" / "*"))
```
Scala compiler seems to pick up the wrong method: `def apply[F[_, _], P, A: Show](value: A)`
rather than
` def apply[F[_, _], P, A: Show](path: A)`
